# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rendr Consulting
email: alonso@rendrconsulting.com
description: > # this means to ignore newlines until "baseurl:"
  At Rendr Consulting, we specialize in custom web application development and mobile app development. Built to help you grow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rendrconsulting.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rendrconsulting
paginate: 9
paginate_path: "blog/:num/"
disqus:
  shortname: rendrconsulting
google_analytics: UA-93796210-1
webmaster_verifications:
  google: sP3dYu3cLfVvtAPx-Occ9K4Z21-MbO2aPo6nlZZ0EYo
logo: "/assets/images/logo.jpg"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - amp-jekyll
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  our_work:
    output: true
    permalink: /our-work/:title
  services:
    output: true
    permalink: /services/:title
